config/routes.rb
Rails.application.routes.draw do

  root 'boards#index'

  resources :boards

  namespace :boards do
    resources :tickets
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :tickets
  validates :title, presence: :true

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :board
  enum status: %w(backlog current_sprint in_progress done)
  validates :title, presence: :true

  scope :backlog, -> { where(status: 0)}
  scope :current_sprint, -> { where(status: 1) }
  scope :in_progress, -> { where(status: 2) }
  scope :done, -> { where(status: 3) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards/tickets_controller.rb
class Boards::TicketsController < ApplicationController

    def show
      @ticket = Ticket.find(params[:id])
    end

    def new
      @status_options = Ticket.statuses.map{|u| [ u[0] ] }
      @ticket = Ticket.new
    end

    def create
      @ticket = Ticket.new(ticket_params)
      if @ticket.save
        flash[:success] = "Successfully created #{@ticket.title}"
        redirect_to boards_ticket_path(@ticket)
      else
        flash[:error] = "Ticket creation failed. Sad days"
        render :new
      end
    end

    def edit
      find_ticket
    end

    def destroy
      find_ticket
      flash[:notice] = "The ticket has been deleted"
      redirect_to root_path
    end

    def update
      find_ticket
      if @ticket.update(ticket_params)
        flash[:success] = "Successfully updated #{@ticket.title}"
        redirect_to boards_ticket_path(@ticket)
      else
        flash[:error] = "ticket update failed. Sad days"
        render :edit
      end
    end

    private

    def find_ticket
      @ticket = ticket.find(params[:id])
    end

    def ticket_params
      params.require(:ticket).permit(:title, :description, :status)
    end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      flash[:success] = "Successfully created #{@board.title}"
      redirect_to board_path(@board)
    else
      flash[:error] = "Board creation failed. Sad days"
      render :new
    end
  end

  def edit
    find_board
  end

  def destroy
    find_board
    flash[:notice] = "The board has been deleted"
    redirect_to root_path
  end

  def update
    find_board
    if @board.update(board_params)
      flash[:success] = "Successfully updated #{@board.title}"
      redirect_to board_path(@board)
    else
      flash[:error] = "Board update failed. Sad days"
      render :edit
    end
  end

  private

  def find_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.htlm.erb
<h1>Editing Your Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Welcome to TrackerHacker</h1>

<% @boards.each do |board| %>

  <%= link_to "#{board.title}", board_path(board), class: "board-link" %>

<% end %>

<%= link_to "New Board", new_board_path %>

app/views/boards/new.html.erb
<h1>Create a New Board!</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong>Title:</strong>
  <%= @board.title %>
</h2>

<%= link_to 'Create a New Ticket', new_boards_ticket_path %> |

<div class="Backlog">
  <h3>Backlog</h3>
  <% @board.tickets.backlog.each do |ticket| %>
    <h4><%= link_to "#{ticket.title}", boards_ticket_path(ticket) %></h4>
    <p>
      <%= ticket.description %>
    </p>
  <% end %>
</div>

<div class="Current-Sprint">
  <h3>Current Sprint</h3>
  <% @board.tickets.current_sprint.each do |ticket| %>
    <h4><%= link_to "#{ticket.title}", boards_ticket_path(ticket) %></h4>
    <p>
      <%= ticket.description %>
    </p>
  <% end %>
</div>

<div class="In-Progress">
  <h3>In Progress</h3>
  <% @board.tickets.in_progress.each do |ticket| %>
    <h4><%= link_to "#{ticket.title}", boards_ticket_path(ticket) %></h4>
    <p>
      <%= ticket.description %>
    </p>
  <% end %>
</div>

<div class="Done">
  <h3>Done</h3>
  <% @board.tickets.done.each do |ticket| %>
    <h4><%= link_to "#{ticket.title}", boards_ticket_path(ticket) %></h4>
    <p>
      <%= ticket.description %>
    </p>
  <% end %>
</div>

<%= link_to 'Edit your board title', edit_board_path(@board) %> |
<%= link_to 'Back to Home', boards_path %>

app/views/boards/tickets/_ticket_form.html.erb
<%= form_for(@ticket, :url => new_boards_ticket_path) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
    <%= f.label :status %><br>
    <%= options_for_select([['backlog', 0], ['current_sprint', 1], ['in_progress', 2], ['done', 3]]) %>
   </div>
  <div class="actions">
    <%= f.submit "Create Ticket" %>
  </div>

<% end %>

app/views/boards/tickets/new.html.erb
<h1>Create a New Ticket!</h1>

<%= render 'ticket_form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong>Title:</strong>
  <%= @ticket.title %>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid">

    <div class="messsages">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "flash-#{name}" %>
      <% end %>
    </div>

    <%= yield %>

  </div>

</body>
</html>